### PR TITLE
Fix hyperlinks in readme

### PR DESCRIPTION
**Pull request by ghost**
ITotalJustice had unintentionally (I hope) left a space between [] and ().

### CODE REVIEW

**Comment by ITotalJustice** [comment]
I genuinely don’t know how those spaces got there. We’re they always there?

**Comment by ghost** [comment]
Hmm. I'm not quite sure. Let me check and I'll get back to you.

**Comment by ghost** [comment]
@ITotalJustice I did some research. https://github.com/ITotalJustice/Yati/commit/4248fa385c5c7123acf75cb62d05b3610f666969#diff-04c6e90faac2675aa89e2176d2eec7d8
This is the commit where you added credits, and have been incorrectly formatted since then.

**Comment by Mz49** [comment]
<@!301363858675597312>

**Pull request merged**
